site_name: Beacon v2 Documentation
site_description: 'Documentation for Beacon v2'
site_author: 'Manuel Rueda, Michael Baudis, Laureen Fromont & Beacon Developers'
copyright: '&copy; Copyright 2021-2022, Beacon v2 Documentation Contributors'
repo_name: 'beacon-v2-unity-testing'
repo_url: https://github.com/ga4gh-beacon/beacon-v2-unity-testing
edit_uri: edit/main/docs/

repo_framework_url: https://github.com/ga4gh-beacon/beacon-v2-unity-testing/tree/main/framework/src
repo_model_url: https://github.com/ga4gh-beacon/beacon-v2-unity-testing/tree/main/models/src

extra_css: [css/theme_overrides.css]

plugins:
    - search
    - with-pdf:
        author: Beacon API Development Team
        output_path: pdf/beacon.pdf
    - macros

markdown_extensions:
    - toc:
        toc_depth: 2-3
        permalink: true
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.saneheaders
    - pymdownx.superfences
    - pymdownx.magiclink:
        hide_protocol: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - mdx_gh_links:
        user: ga4gh-beacon
        repo: beacon-v2-unity-testing
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
    - Introduction to Beacon v2: index.md
    - Documentation Scopes: roles.md
    - Changes: bugs-changes-log.md
    - Beacon Types and Examples:
        - Beacon Flavours: beacon-flavours.md
        - Genomic Query Examples: variant-queries.md
        - Implementations and Networks: implementations-and-networks.md
    - Implement & Deploy a Beacon:
        - Deployment Options: implement-and-deploy.md
        - Standards Integration: formats-standards.md
        - Beacon Reference Implementation &#8599;: https://b2ri-documentation.readthedocs.io/en/latest/
    - Beacon Components:
        - Framework: framework.md         
        - Models: models.md
        - Filters: filters.md
        - REST API: rest-api.md
        - Terms List: schemas-md/beacon_terms.md
    - Schemas:
        - Analyses: schemas-md/analyses_defaultSchema.md
        - Biosamples: schemas-md/biosamples_defaultSchema.md
        - Cohorts: schemas-md/cohorts_defaultSchema.md
        - Datasets: schemas-md/datasets_defaultSchema.md
        - Genomic Variations: schemas-md/genomicVariations_defaultSchema.md
        - Individuals: schemas-md/individuals_defaultSchema.md
        - Runs: schemas-md/runs_defaultSchema.md        
    - External Links:
        - Beacon Project &#8599;: http://beacon-project.io
        - Github Repositories &#8599;: https://github.com/ga4gh-beacon/
        - Read the Docs Version &#8599;: https://beacon-v2-unity.readthedocs.io/en/latest/
    - Download PDF: pdf/beacon.pdf

theme:
    # name: readthedocs
    # name: windmill
    name: material
    logo: img/GA-logo.png
    favicon: img/ga4gh_circle.ico
    icon:
        repo: fontawesome/brands/github-alt 
    palette:
        primary: teal
    features:
        - search.highlight
        - search.share
        - navigation.instant
        - navigation.tracking
        - navigation.sections

# Options
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/genomebeacons
    - icon: fontawesome/brands/github 
      link: https://github.com/ga4gh-beacon

# https://pypi.org/project/mkdocs-with-pdf/ for more PDF configuration ...
